version: '2'
networks:
  youtube_scraper:
    external: true
services:

  redis:
    image: redis
    ports:
      - 6379:6379
    expose:
      - "6379"
    container_name: cache
    command: sh -c 'redis-server --bind 0.0.0.0'
    networks:
      - youtube_scraper
  node:
    tty: true # Enables debugging capabilities when attached to this container.
    image: 'docker.io/bitnami/node:12-debian-10'
    command: sh -c 'npm install && node app'
    ports:
      - 3001:3000
    volumes:
      - .:/app
    links:
      - redis
    environment:
      - REDIS_URL=redis://cache
    networks:
      - youtube_scraper
