version: '2'

services:

  redis:
    image: redis
    container_name: cache
    expose:
      - 6379
  node:
    tty: true # Enables debugging capabilities when attached to this container.
    image: 'docker.io/bitnami/node:12-debian-10'
    command: sh -c 'npm install && node app'
    ports:
      - 3000:3000
    volumes:
      - .:/app
    links:
      - redis
    environment:
      - REDIS_URL=redis://cache