version: '2'

services:

  redis:
    networks:
      - youtube
    image: redis
    ports:
      - 6379:6379
    expose:
      - "6379"
    container_name: youtube_cache
    command: sh -c 'redis-server --bind 0.0.0.0'

  node:
    tty: true # Enables debugging capabilities when attached to this container.
    image: 'docker.io/bitnami/node:12-debian-10'
    command: sh -c 'npm install && npm rebuild && node app'
    volumes:  
      - .:/app
    links:
      - redis
    environment:
      - REDIS_URL=redis://youtube_cache
    container_name: youtube_scraper
    networks:
      - youtube

networks:
  youtube:
    external: true
